Added Content-encoding to gzip
Wolox/aws-deploy-script-frontend pull request #12
Opened 2019-08-22 13:21 UTC by rlajous

## Summary
- Added Content-Encoding metadata by a command if you wanna deploy a gziped file

2019-08-22 13:52 UTC, damfinkel requested changes

2019-08-22 13:52 UTC, damfinkel commented on script/s3.js
> +  else {
else in the previous line

2019-08-22 13:52 UTC, damfinkel commented on script/s3.js
> +    return {...metaData, ContentEncoding: 'gzip'};
```suggestion
    return { ...metaData, ContentEncoding: 'gzip' };
```

2019-08-22 13:52 UTC, damfinkel commented on script/s3.js
> +  if (gzip){
```suggestion
  if (gzip) {
```

2019-08-22 13:52 UTC, damfinkel commented on script/s3.js
> +const isGzip = metaData => {
I'd rename this to `getMetadataObject`. If named `isGzip` it appears to be a function returning a boolean

2019-08-22 14:25 UTC, damfinkel submitted a review, later dismissed

2019-08-23 13:11 UTC, SKOLZ submitted a review, later dismissed

2019-08-23 14:42 UTC, SKOLZ requested changes

2019-08-23 14:42 UTC, SKOLZ commented on script/s3.js
> +let gzip = false;
I'd remove the if in the following line and set this to:
```
const gzip = args.gzip || args.g;
```

2019-08-23 14:55 UTC, SKOLZ approved these changes

2019-08-23 15:19 UTC, damfinkel approved these changes

2019-08-23 15:30 UTC, FrankIglesias approved these changes

2019-08-23 15:32 UTC, merged